[package]
name = "rudis"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
bytes = "1"

[lib]
name = "rudis"
path = "src/lib.rs"

[[bin]]
name = "rudis"
#name = "server"
path = "src/bin/server.rs"

[[bin]]
name = "cli"
path = "src/bin/cli.rs"
